#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd)
cd "${SCRIPT_DIR}"

XEN_VERSION="${1}"
OUR_PATCHES_VERSION="${2}"

TAG="${XEN_VERSION}-gentoo-patchset-${OUR_PATCHES_VERSION}"
DESCRIPTION="Gentoo specific patches for ${XEN_VERSION} (or later)"

git commit \
	--signoff \
	-m "${DESCRIPTION}"

git tag \
	-s \
	-m "${DESCRIPTION}" \
	"${TAG}"
